#!/bin/bash

WITH_CPANM=1
CPANM_VERSION=""
WITH_CARTON=1
CARTON_VERSION=""

usage() {
    echo "Usage:"
    echo "  $0 VERSION LOCATION [OPTIONS...]"
    echo "Options:"
    echo "  --help                     display this help and exit"
    echo "  --with-cpanm               install cpanm [default]"
    echo "  --without-cpanm            don't install cpanm"
    echo "  --cpanm-version VERSION    specify cpanm version"
    echo "  --with-carton              install carton [default]"
    echo "  --without-carton           don't install carton"
    echo "  --carton-version VERSION   specify carton version"
}

OPTS=`getopt -o h --long help,with-cpanm,without-cpanm,cpanm-version:,with-carton,without-carton,carton-version: -- "$@"`
[ $? -ne 0 ] && usage && exit 1

eval set -- "$OPTS"

while true; do
    case "$1" in
        --help)           usage && exit 0;;
        --with-cpanm)     WITH_CPANM=1;        shift;;
        --without-cpanm)  WITH_CPANM=0;        shift;;
        --cpanm-version)  CPANM_VERSION="$2";  shift 2;;
        --with-carton)    WITH_CARTON=1;       shift;;
        --without-carton) WITH_CARTON=0;       shift;;
        --carton-version) CARTON_VERSION="$2"; shift 2;;
        --) shift; break;;
    esac
done

TARGET_VERSION=$1
PREFIX=$2

if [ "x"$TARGET_VERSION = "x" -o "x"$PREFIX = "x" ]; then
    usage
    exit 0
fi

cd $(dirname $0)

set -e
mkdir -p ./bin
curl -s https://raw.github.com/tokuhirom/Perl-Build/master/perl-build > ./bin/perl-build
curl -s -L http://cpanmin.us/ > ./bin/fatpack_cpanm
set +e

echo "Start to build perl $TARGET_VERSION ..."
perl ./bin/perl-build -DDEBUGGING=-g $TARGET_VERSION $PREFIX > /tmp/$USER-perl-install.log 2>&1
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "perl-build failed. see log: /tmp/$USER-perl-install.log"
    exit 1
fi

if [ $WITH_CPANM -eq 1 ]; then
    [ x$CPANM_VERSION != "x" ] && CPANM_VERSION="@$CPANM_VERSION"
    CARTON=""
    if [ $WITH_CARTON -eq 1 ]; then
        CARTON="Carton"
        [ x$CARTON_VERSION != "x" ] && CARTON_VERSION="@$CARTON_VERSION"
    fi

    $PREFIX/bin/perl ./bin/fatpack_cpanm --notest App::cpanminus$CPANM_VERSION $CARTON$CARTON_VERSION > /tmp/$USER-perl-install-cpanm.log 2>&1
    RETVAL=$?
    if [ $RETVAL != 0 ]; then
        echo "failed to install cpanm/carton. see log: /tmp/$USER-perl-install-cpanm.log"
        exit 2
    fi
fi

echo "perl $TARGET_VERSION (and cpanm/carton) successfully installed on $PREFIX"
echo "To use this perl, do 'export PATH=$PREFIX/bin:\$PATH'."
