#!/bin/bash

TARGET_VERSION=""
PREFIX=""
CONFIGURE_OPTIONS=""

usage() {
    echo "Usage:"
    echo "  $0 --target VERSION --prefix PATH [OPTIONS...] [-- CONFIGURE_OPTIONS]"
    echo "Options:"
    echo "  --help                     display this help and exit"
    echo "  --target VERSION           target version to install"
    echo "  --prefix PATH              path prefix"
}

OPTS=`getopt -o h --long help,target:,prefix: -- "$@"`
[ $? -ne 0 ] && usage && exit 1

eval set -- "$OPTS"

while true; do
    case "$1" in
        --help)           usage && exit 0;;
        --target)         TARGET_VERSION="$2"; shift 2;;
        --prefix)         PREFIX="$2";         shift 2;;
        --) shift; break;;
    esac
done
CONFIGURE_OPTIONS=$@

if [ "x"$TARGET_VERSION = "x" -o "x"$PREFIX = "x" ]; then
    usage
    exit 0
fi

cd $(dirname $0)
XBUILD_PATH=$(pwd)

if [ ! -d ./var/php-build ]; then
    (
        set -e
        mkdir -p var
        cd var
        git clone -q git://github.com/CHH/php-build.git php-build-repo
        cd php-build-repo
        PREFIX=$XBUILD_PATH/var/php-build ./install.sh >/dev/null 2>&1
    ) || (echo "failed to download php-build" && exit 1)
fi

echo "Start to build php $TARGET_VERSION ..."
PHP_BUILD_CONFIGURE_OPTS="$CONFIGURE_OPTIONS" ./var/php-build/bin/php-build $TARGET_VERSION $PREFIX > /tmp/$USER-php-install.log 2>&1
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "php-build failed. see log: /tmp/$USER-php-install.log"
    exit 1
fi

echo "php $TARGET_VERSION successfully installed on $PREFIX"
echo "To use this php, do 'export PATH=$PREFIX/bin:\$PATH'."
