#!/bin/bash

usage() {
    echo "Usage:"
    echo "  $0 VERSION LOCATION [OPTIONS...]"
    echo "Options:"
    echo "  --help                     display this help and exit"
}

OPTS=`getopt -o h --long help -- "$@"`
[ $? -ne 0 ] && usage && exit 1

eval set -- "$OPTS"

while true; do
    case "$1" in
        --help)           usage && exit 0;;
        --) shift; break;;
    esac
done

TARGET_VERSION=$1
PREFIX=$2

if [ "x"$TARGET_VERSION = "x" -o "x"$PREFIX = "x" ]; then
    usage
    exit 0
fi

cd $(dirname $0)
XBUILD_PATH=$(pwd)

if [ ! -d ./var/python-build ]; then
    (
        set -e
        mkdir -p var
        cd var
        git clone -q git://github.com/yyuu/pyenv.git pyenv-repo
        cd pyenv-repo/plugins/python-build
        PREFIX=$XBUILD_PATH/var/python-build ./install.sh >/dev/null 2>&1
    ) || (echo "failed to download python-build" && exit 1)
fi

echo "Start to build python $TARGET_VERSION ..."
./var/python-build/bin/python-build $TARGET_VERSION $PREFIX > /tmp/$USER-python-install.log 2>&1
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "python-build failed. see log: /tmp/$USER-python-install.log"
    exit 1
fi

echo "python $TARGET_VERSION successfully installed on $PREFIX"
echo "To use this python, do 'export PATH=$PREFIX/bin:\$PATH'."
