#!/bin/bash

TARGET_VERSION=""
PREFIX=""

usage() {
    echo "Usage:"
    echo "  $0 --target VERSION --prefix PATH [OPTIONS...]"
    echo "Options:"
    echo "  --help                     display this help and exit"
    echo "  --target VERSION           target version to install"
    echo "  --prefix PATH              path prefix"
}

OPTS=`getopt -o h --long help,target:,prefix: -- "$@"`
[ $? -ne 0 ] && usage && exit 1

eval set -- "$OPTS"

while true; do
    case "$1" in
        --help)           usage && exit 0;;
        --target)         TARGET_VERSION="$2"; shift 2;;
        --prefix)         PREFIX="$2";         shift 2;;
        --) shift; break;;
    esac
done

if [ "x"$TARGET_VERSION = "x" -o "x"$PREFIX = "x" ]; then
    usage
    exit 0
fi

cd $(dirname $0)
XBUILD_PATH=$(pwd)

mkdir -p var
oldcheck=$(find var -name "ruby-build.date" -mtime -1)
if [ ! -f ./var/ruby-build.date -o "x"$oldcheck = "x" ]; then
    (
        echo "cloning latest ruby-build."
        set -e
        cd var
        [ -d ./ruby-build ] && rm -rf ruby-build-repo ruby-build ruby-build.date
        git clone -q git://github.com/sstephenson/ruby-build.git ruby-build-repo
        touch ruby-build.date
        cd ruby-build-repo
        PREFIX=$XBUILD_PATH/var/ruby-build ./install.sh >/dev/null 2>&1
    ) || (echo "failed to download ruby-build" && exit 1)
fi
rm -f ./var/.24hours

echo "Start to build ruby $TARGET_VERSION ..."
./var/ruby-build/bin/ruby-build $TARGET_VERSION $PREFIX > /tmp/$USER-ruby-install.log 2>&1
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "ruby-build failed. see log: /tmp/$USER-ruby-install.log"
    exit 1
fi

(
    export PATH=$PREFIX/bin:$PATH
    $PREFIX/bin/gem install --no-rdoc --no-ri bundler pry > /tmp/$USER-ruby-install-bundler.log 2>&1
) || (echo "gem install failed. see log /tmp/$USER-ruby-install-bundler.log" && exit 2)

echo "ruby $TARGET_VERSION successfully installed on $PREFIX"
echo "To use this ruby, do 'export PATH=$PREFIX/bin:\$PATH'."
